#!/bin/bash

# svn checkout this to, for example, ~/installed/tyler-shell and then run script/install

cd `dirname $0`/..
package_dir=`bin/realpath .`
#echo $package_dir

touch ~/.bashrc
grep "bash/bashrc" ~/.bashrc > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bashrc"
	echo "source $package_dir/bash/bashrc" >> ~/.bashrc
fi

touch ~/.bash_profile
grep "bash/bash_profile" ~/.bash_profile > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bash_profile"
	echo "source $package_dir/bash/bash_profile" >> ~/.bash_profile
fi

touch ~/.bash_logout
grep "bash/bash_logout" ~/.bash_logout > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bash_logout"
	echo "source $package_dir/bash/bash_logout" >> ~/.bash_logout
fi

[   -e ~/.irbrc ]   && echo "~/.irbrc already exists'" && diff ~/.irbrc $package_dir/.irbrc
[ ! -e ~/.irbrc ] && cp $package_dir/.irbrc ~/.irbrc 

mkdir -p ~/.paths.d

mkdir -p ~/installed
pushd    ~/installed
git clone git://github.com/TylerRick/ruby-git.git
git clone git://github.com/TylerRick/tyler-git.git
git clone git://gitorious.org/willgit/mainline.git/ willgit
popd

echo '~/installed/tyler-git/bin' > ~/.paths.d/tyler-git
echo '~/installed/willgit/bin'   > ~/.paths.d/willgit
