#!/bin/bash

# to do: move to ~/installed/tyler-shell
#packageDir="~/public/shell"      # this said couldn't stat when used with diff $packageDir/.irbrc, so I guess let's expand it
packageDir=`echo ~/public/shell`
#echo $packageDir

touch ~/.bashrc
grep "bash/bashrc" ~/.bashrc > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bashrc"
	echo "source $packageDir/bash/bashrc" >> ~/.bashrc
fi

touch ~/.bash_profile
grep "bash/bash_profile" ~/.bash_profile > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bash_profile"
	echo "source $packageDir/bash/bash_profile" >> ~/.bash_profile
fi

touch ~/.bash_logout
grep "bash/bash_logout" ~/.bash_logout > /dev/null
if [[ "$?" == "1" ]]; then
	echo "Installing bash/bash_logout"
	echo "source $packageDir/bash/bash_logout" >> ~/.bash_logout
fi

[   -e ~/.irbrc ]   && echo "~/.irbrc already exists'" && diff ~/.irbrc $packageDir/.irbrc
[ ! -e ~/.irbrc ] && cp $packageDir/.irbrc ~/.irbrc 

mkdir -p ~/.paths.d

mkdir -p ~/installed
pushd    ~/installed
git clone git://github.com/TylerRick/ruby-git.git
git clone git://github.com/TylerRick/tyler-git.git
git clone git://gitorious.org/willgit/mainline.git/ willgit
popd

echo '~/installed/tyler-git/bin' > ~/.paths.d/tyler-git
echo '~/installed/willgit/bin'   > ~/.paths.d/willgit
