#!/usr/bin/env python

import sys, os

if len(sys.argv) == 1:
	path = "./"
else:
	path = sys.argv[1]

command = """grep -Rn "[^ \\t\\r\\n]" """ + path + """* | grep -v "\.svn" | grep "[^:]*\(html\|php\|py\|dist\|xml\|tex\|pl\|sql\):" | wc"""
pipe = os.popen(command, "r")
results = pipe.read()
pipe.close()
print results.split()[0]
