#!/usr/bin/env python
# Given a revision number, it lists all files that have been added, modified, or removed.

import os, sys, re

if __name__ == "__main__":
	pipe = os.popen("svn log -rHEAD:" + sys.argv[1] + " -v | egrep \"^   [AMD]\" | sed \"s/   //\"")
	pipeResults = pipe.readlines()
	pipe.close()

	finalResults = {"A": [], "M": [], "D": []}
	touchedFiles = []

	for line in pipeResults:
		line = line.strip().split(" ")
		if line[1] not in touchedFiles:
			touchedFiles.append(line[1])
			finalResults[line[0]].append(line[1][1:])

	for key in finalResults.keys():
		finalResults[key].sort()

	print "Added:"
	for item in finalResults["A"]:
		print " " + item
	print

	print "Modified:"
	for item in finalResults["M"]:
		print " " + item
	print

	print "Removed:"
	for item in finalResults["D"]:
		print " " + item
	print

